=== chaijewon/2023-03-28-WebStudy/JSPMVCFinalProject/src/main/webapp/xml/sawon.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
   <sawon> = table 문서형 데이터베이스 
     <list> = row
       <name></name> = column
       <sex></sex> = column
       <phone></phone> = column
     </list>
     <list>
       <name></name>
       <sex></sex>
       <phone></phone>
     </list>
     <list>
       <name></name>
       <sex></sex>
       <tel></tel>
     </list>
   </sawon>
     기호 
      1. * : 0이상 사용이 가능 
      2. + : 1이상 사용이 가능
      3. ? : 사용/미사용
      4. | : 선택 
      5. def : 한번만 사용이 가능 
      6. #PCDATA = 태그와 태그사이의 문자열
 -->
 <!ELEMENT sawon (list)*>
 <!ELEMENT list (name,sex,(phone|tel))>
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT sex (#PCDATA)>
 <!ELEMENT phone (#PCDATA)>
 <!ELEMENT tel (#PCDATA)>

=== chaijewon/2023-03-28-WebStudy/JSPMVCFinalProject/src/main/webapp/xml/sawon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sawon SYSTEM "sawon.dtd">
<sawon>
 <list>
  <name>홍길동</name>
  <sex>남자</sex>
  <phone>1111-1111</phone>
 </list>
 <list>
  <name>홍길동</name>
  <sex>남자</sex>
  <phone>1111-1111</phone>
 </list>
</sawon>
